#!/bin/sh

sudo apt-get install -y python-pip
pip install GitPython==1.0.1
pip install gitdb==0.6.4
pip install smmap==0.9.0
pip install stomp.py==4.1.2
pip install wsgiref==0.1.2
chmod 0755 /opt/ems-public/ems.sh
chmod 0755 /etc/openbaton/ems/conf.ini
