#!/bin/sh
DIR=/opt/openbaton/ems
PROG="/usr/bin/python"
ARG="/opt/openbaton/ems"
DAEMON_USER=root
PID_FILE=/var/run/openbaton-ems.pid

. /etc/init.d/functions

start() {
        echo "Starting EMS"
        #daemon --user $DAEMON_USER $PROG $ARG &
        ${PROG} ${ARG} &
        echo "$!" > ${PID_FILE}
        cat ${PID_FILE}
}

stop() {
        echo "Stopping EMS"
        kill $(cat ${PID_FILE})
}

restart() {
        echo "Restarting EMS"
        stop
        start
}

case "$1" in
    "start" )
        start ;;
    "stop" )
        stop ;;
    "restart" )
        restart;;
    * )
    usage;;
esac